generation_documents_task:
  description: >
    Generate exactly {docs_per_topic} documents ONCE for each topic in the knowledge base: {topic}.
    Use the generate_documents_as_files tool with topics={topics}, docs_per_topic={docs_per_topic}, max_tokens_per_doc={max_tokens_per_doc}, batch_size={batch_size}.
    DO NOT repeat document generation for the same topics.
    Each document will be saved as an individual JSON file in a structured directory format.
    This approach ensures clean separation between documents and eliminates JSON parsing issues.
  expected_output: >
    JSON response from generate_documents_as_files tool confirming that exactly {docs_per_topic} individual JSON files per topic have been created for all {topics} topics.
    Return the complete response including file paths and generation statistics.
  agent: document_generator

create_database_task:
  description: >
    Create the RAG database ONCE for storing generated documents using the create_vectordb tool.
    DO NOT repeat database creation if it already exists.
  expected_output: >
    Confirmation message from create_vectordb tool that the database has been successfully created.
  agent: database_engineer

store_documents_task:
  description: >
    Load and store ALL individual document JSON files created by the generation_documents_task.
    
    Use the store_individual_documents tool which will:
    1. Find all JSON document files in the documents directory
    2. Load each file individually (no JSON parsing issues)
    3. Create chunks from each document separately
    4. Store all chunks in the vector database with proper metadata
    
    Call: store_individual_documents()
    
    This approach processes each document file individually, ensuring proper topic/subject separation
    and eliminating the JSON parsing issues from the previous approach.
  expected_output: >
    Detailed JSON response from store_individual_documents tool showing:
    - Number of document files processed
    - Number of chunks created and stored
    - Distribution of chunks by subject/topic
    - Complete success confirmation for all medicine, football, and technology documents
  agent: database_engineer