retrieve_medical_info:
  description: "Search the medical vector database for relevant information about {topic} based on the query: {query}"
  expected_output: "Relevant medical documents and citations from the vector database"
  agent: medical_researcher
  
synthesize_medical_response:
  description: "Create a comprehensive medical response based on retrieved information about {topic}. Ensure all claims are supported by the retrieved documents."
  expected_output: "A detailed medical response with proper citations in GuideOutline format"
  agent: medical_analyst
  context:
    - retrieve_medical_info